print("hello world")
print("how are you?")
print("hi")
print("hi2")
print("hi23")
print("helllllo")
print("hi23")
print("hello world")
print("how are you?")
print("hi")
print("hi23")
print("hello world")
print("how are you?")
print("hi")
print("hi23")
print("hello world")
print("how are you?")
print("hi")
print("hi23")
print("hello world")
print("how are you?")
print("hi")
print("hi23")
